model:
<<<<<<< HEAD
  arch: mini_gpt4_llama_v2
=======
  arch: mini_gpt4_llama_v2_rppg
>>>>>>> 7ee24512cec60775ff9cc2794956508e6d119a57
  model_type: pretrain_vicuna
  freeze_vit: True
  freeze_qformer: True
  max_txt_len: 512
<<<<<<< HEAD
  low_resource: False
=======
  low_resource: True
>>>>>>> 7ee24512cec60775ff9cc2794956508e6d119a57
  image_size: 224
  end_sym: "</s>"
  llama_model: "mistralai/Mistral-7B-Instruct-v0.2"
  ckpt: "/home/tony/MiniGPT4-video/checkpoints/video_mistral_checkpoint_best.pth"
  # ckpt: "/home/tony/nvme2tb/mistral_rppg_mamba_half/202407300139/checkpoint_49.pth" 
  #"checkpoints/video_mistral_all_checkpoint_last.pth"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16
  length: 50
  use_grad_checkpoint_llm: True
  max_context_len: 3600 #7200
<<<<<<< HEAD
  # device: "cuda:0"
=======
  device: "cuda:0"
>>>>>>> 7ee24512cec60775ff9cc2794956508e6d119a57

datasets:
  engagenet_rppg: #99378 row  - 13224 video
    batch_size: 1
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 200


run:
  task: image_text_pretrain
  seed: 42
  amp: True
<<<<<<< HEAD
  device: "cuda"
=======
  device: "cuda:0"
>>>>>>> 7ee24512cec60775ff9cc2794956508e6d119a57
